export const machines = [
    {
        "name": "AJRouter",
        "status": "Stopped"
    }, {
        "name": "ALG",
        "status": "Stopped"
    }, {
        "name": "AppIDSvc",
        "status": "Stopped"
    }, {
        "name": "Appinfo",
        "status": "Running"
    }, {
        "name": "AppMgmt",
        "status": "Stopped"
    }, {
        "name": "AppReadiness",
        "status": "Stopped"
    }, {
        "name": "AppVClient",
        "status": "Stopped"
    }, {
        "name": "AppXSvc",
        "status": "Stopped"
    }, {
        "name": "aspnet_state",
        "status": "Stopped"
    }, {
        "name": "AssignedAccessManagerSvc",
        "status": "Stopped"
    }, {
        "name": "AudioEndpointBuilder",
        "status": "Running"
    }, {
        "name": "Audiosrv",
        "status": "Running"
    }, {
        "name": "autotimesvc",
        "status": "Stopped"
    }, {
        "name": "AxInstSV",
        "status": "Stopped"
    }, {
        "name": "BDESVC",
        "status": "Stopped"
    }, {
        "name": "BFE",
        "status": "Running"
    }, {
        "name": "BITS",
        "status": "Running"
    }, {
        "name": "BrokerInfrastructure",
        "status": "Running"
    }, {
        "name": "BTAGService",
        "status": "Stopped"
    }, {
        "name": "BthAvctpSvc",
        "status": "Running"
    }, {
        "name": "bthserv",
        "status": "Stopped"
    }, {
        "name": "camsvc",
        "status": "Stopped"
    }, {
        "name": "CDPSvc",
        "status": "Running"
    }, {
        "name": "CertPropSvc",
        "status": "Stopped"
    }, {
        "name": "ClipSVC",
        "status": "Stopped"
    }, {
        "name": "com.docker.service",
        "status": "Running"
    }, {
        "name": "COMSysApp",
        "status": "Stopped"
    }, {
        "name": "CoreMessagingRegistrar",
        "status": "Running"
    }, {
        "name": "CryptSvc",
        "status": "Running"
    }, {
        "name": "CscService",
        "status": "Stopped"
    }, {
        "name": "DcomLaunch",
        "status": "Running"
    }, {
        "name": "defragsvc",
        "status": "Stopped"
    }, {
        "name": "DeviceAssociationService",
        "status": "Stopped"
    }, {
        "name": "DeviceInstall",
        "status": "Running"
    }, {
        "name": "DevQueryBroker",
        "status": "Running"
    }, {
        "name": "Dhcp",
        "status": "Running"
    }, {
        "name": "diagnosticshub.standardcollector.service",
        "status": "Stopped"
    }, {
        "name": "diagsvc",
        "status": "Stopped"
    }, {
        "name": "DiagTrack",
        "status": "Running"
    }, {
        "name": "DispBrokerDesktopSvc",
        "status": "Running"
    }, {
        "name": "DisplayEnhancementService",
        "status": "Stopped"
    }, {
        "name": "DmEnrollmentSvc",
        "status": "Stopped"
    }, {
        "name": "dmwappushservice",
        "status": "Stopped"
    }, {
        "name": "Dnscache",
        "status": "Running"
    }, {
        "name": "DoSvc",
        "status": "Running"
    }, {
        "name": "dot3svc",
        "status": "Stopped"
    }, {
        "name": "DPS",
        "status": "Running"
    }, {
        "name": "DsmSvc",
        "status": "Stopped"
    }, {
        "name": "DsSvc",
        "status": "Running"
    }, {
        "name": "DusmSvc",
        "status": "Running"
    }, {
        "name": "Eaphost",
        "status": "Stopped"
    }, {
        "name": "edgeupdate",
        "status": "Stopped"
    }, {
        "name": "edgeupdatem",
        "status": "Stopped"
    }, {
        "name": "EFS",
        "status": "Stopped"
    }, {
        "name": "embeddedmode",
        "status": "Stopped"
    }, {
        "name": "EntAppSvc",
        "status": "Stopped"
    }, {
        "name": "EventLog",
        "status": "Running"
    }, {
        "name": "EventSystem",
        "status": "Running"
    }, {
        "name": "Fax",
        "status": "Stopped"
    }, {
        "name": "fdPHost",
        "status": "Stopped"
    }, {
        "name": "FDResPub",
        "status": "Stopped"
    }, {
        "name": "fhsvc",
        "status": "Stopped"
    }, {
        "name": "FontCache",
        "status": "Running"
    }, {
        "name": "FrameServer",
        "status": "Stopped"
    }, {
        "name": "GamingServices",
        "status": "Running"
    }, {
        "name": "GamingServicesNet",
        "status": "Running"
    }, {
        "name": "GoogleChromeElevationService",
        "status": "Stopped"
    }, {
        "name": "gpsvc",
        "status": "Stopped"
    }, {
        "name": "GraphicsPerfSvc",
        "status": "Stopped"
    }, {
        "name": "gupdate",
        "status": "Stopped"
    }, {
        "name": "gupdatem",
        "status": "Stopped"
    }, {
        "name": "hidserv",
        "status": "Running"
    }, {
        "name": "hns",
        "status": "Running"
    }, {
        "name": "HvHost",
        "status": "Running"
    }, {
        "name": "icssvc",
        "status": "Stopped"
    }, {
        "name": "IKEEXT",
        "status": "Stopped"
    }, {
        "name": "InstallService",
        "status": "Running"
    }, {
        "name": "iphlpsvc",
        "status": "Running"
    }, {
        "name": "IpxlatCfgSvc",
        "status": "Stopped"
    }, {
        "name": "JetBrainsEtwHost",
        "status": "Running"
    }, {
        "name": "KeyIso",
        "status": "Running"
    }, {
        "name": "KtmRm",
        "status": "Stopped"
    }, {
        "name": "LanmanServer",
        "status": "Running"
    }, {
        "name": "LanmanWorkstation",
        "status": "Running"
    }, {
        "name": "lfsvc",
        "status": "Running"
    }, {
        "name": "LicenseManager",
        "status": "Running"
    }, {
        "name": "lltdsvc",
        "status": "Stopped"
    }, {
        "name": "lmhosts",
        "status": "Running"
    }, {
        "name": "LSM",
        "status": "Running"
    }, {
        "name": "LxpSvc",
        "status": "Stopped"
    }, {
        "name": "LxssManager",
        "status": "Running"
    }, {
        "name": "MapsBroker",
        "status": "Stopped"
    }, {
        "name": "MicrosoftEdgeElevationService",
        "status": "Stopped"
    }, {
        "name": "MozillaMaintenance",
        "status": "Stopped"
    }, {
        "name": "mpssvc",
        "status": "Running"
    }, {
        "name": "MSDTC",
        "status": "Stopped"
    }, {
        "name": "MSiSCSI",
        "status": "Stopped"
    }, {
        "name": "msiserver",
        "status": "Stopped"
    }, {
        "name": "NaturalAuthentication",
        "status": "Stopped"
    }, {
        "name": "NcaSvc",
        "status": "Stopped"
    }, {
        "name": "NcbService",
        "status": "Running"
    }, {
        "name": "NcdAutoSetup",
        "status": "Stopped"
    }, {
        "name": "Netlogon",
        "status": "Stopped"
    }, {
        "name": "Netman",
        "status": "Stopped"
    }, {
        "name": "netprofm",
        "status": "Running"
    }, {
        "name": "NetSetupSvc",
        "status": "Stopped"
    }, {
        "name": "NetTcpPortSharing",
        "status": "Stopped"
    }, {
        "name": "NgcCtnrSvc",
        "status": "Stopped"
    }, {
        "name": "NgcSvc",
        "status": "Stopped"
    }, {
        "name": "NlaSvc",
        "status": "Running"
    }, {
        "name": "nsi",
        "status": "Running"
    }, {
        "name": "nvagent",
        "status": "Running"
    }, {
        "name": "NVDisplay.ContainerLocalSystem",
        "status": "Running"
    }, {
        "name": "p2pimsvc",
        "status": "Stopped"
    }, {
        "name": "p2psvc",
        "status": "Stopped"
    }, {
        "name": "PanGPS",
        "status": "Running"
    }, {
        "name": "PcaSvc",
        "status": "Running"
    }, {
        "name": "PeerDistSvc",
        "status": "Stopped"
    }, {
        "name": "perceptionsimulation",
        "status": "Stopped"
    }, {
        "name": "PerfHost",
        "status": "Stopped"
    }, {
        "name": "PhoneSvc",
        "status": "Stopped"
    }, {
        "name": "pla",
        "status": "Stopped"
    }, {
        "name": "PlugPlay",
        "status": "Running"
    }, {
        "name": "PNRPAutoReg",
        "status": "Stopped"
    }, {
        "name": "PNRPsvc",
        "status": "Stopped"
    }, {
        "name": "PolicyAgent",
        "status": "Running"
    }, {
        "name": "Power",
        "status": "Running"
    }, {
        "name": "PrintNotify",
        "status": "Stopped"
    }, {
        "name": "ProfSvc",
        "status": "Running"
    }, {
        "name": "PushToInstall",
        "status": "Stopped"
    }, {
        "name": "QWAVE",
        "status": "Running"
    }, {
        "name": "RasAuto",
        "status": "Stopped"
    }, {
        "name": "RasMan",
        "status": "Stopped"
    }, {
        "name": "Razer Chroma SDK Server",
        "status": "Running"
    }, {
        "name": "Razer Chroma SDK Service",
        "status": "Running"
    }, {
        "name": "Razer Game Manager Service",
        "status": "Running"
    }, {
        "name": "Razer Synapse Service",
        "status": "Running"
    }, {
        "name": "RemoteAccess",
        "status": "Stopped"
    }, {
        "name": "RemoteRegistry",
        "status": "Stopped"
    }, {
        "name": "RetailDemo",
        "status": "Stopped"
    }, {
        "name": "RmSvc",
        "status": "Running"
    }, {
        "name": "RpcEptMapper",
        "status": "Running"
    }, {
        "name": "RpcLocator",
        "status": "Stopped"
    }, {
        "name": "RpcSs",
        "status": "Running"
    }, {
        "name": "RzActionSvc",
        "status": "Running"
    }, {
        "name": "SamSs",
        "status": "Running"
    }, {
        "name": "SCardSvr",
        "status": "Stopped"
    }, {
        "name": "ScDeviceEnum",
        "status": "Stopped"
    }, {
        "name": "Schedule",
        "status": "Running"
    }, {
        "name": "SCPolicySvc",
        "status": "Stopped"
    }, {
        "name": "SDRSVC",
        "status": "Stopped"
    }, {
        "name": "seclogon",
        "status": "Stopped"
    }, {
        "name": "SecurityHealthService",
        "status": "Running"
    }, {
        "name": "SEMgrSvc",
        "status": "Running"
    }, {
        "name": "SENS",
        "status": "Running"
    }, {
        "name": "Sense",
        "status": "Stopped"
    }, {
        "name": "SensorDataService",
        "status": "Stopped"
    }, {
        "name": "SensorService",
        "status": "Stopped"
    }, {
        "name": "SensrSvc",
        "status": "Stopped"
    }, {
        "name": "SessionEnv",
        "status": "Stopped"
    }, {
        "name": "SgrmBroker",
        "status": "Running"
    }, {
        "name": "SharedAccess",
        "status": "Running"
    }, {
        "name": "SharedRealitySvc",
        "status": "Stopped"
    }, {
        "name": "ShellHWDetection",
        "status": "Running"
    }, {
        "name": "shpamsvc",
        "status": "Stopped"
    }, {
        "name": "smphost",
        "status": "Stopped"
    }, {
        "name": "SmsRouter",
        "status": "Stopped"
    }, {
        "name": "SNMPTRAP",
        "status": "Stopped"
    }, {
        "name": "spectrum",
        "status": "Stopped"
    }, {
        "name": "Spooler",
        "status": "Running"
    }, {
        "name": "sppsvc",
        "status": "Stopped"
    }, {
        "name": "SQLWriter",
        "status": "Running"
    }, {
        "name": "SSDPSRV",
        "status": "Running"
    }, {
        "name": "ssh-agent",
        "status": "Stopped"
    }, {
        "name": "SstpSvc",
        "status": "Stopped"
    }, {
        "name": "StateRepository",
        "status": "Running"
    }, {
        "name": "Steam Client Service",
        "status": "Stopped"
    }, {
        "name": "stisvc",
        "status": "Stopped"
    }, {
        "name": "StorSvc",
        "status": "Running"
    }, {
        "name": "svsvc",
        "status": "Stopped"
    }, {
        "name": "swprv",
        "status": "Stopped"
    }, {
        "name": "SysMain",
        "status": "Running"
    }, {
        "name": "SystemEventsBroker",
        "status": "Running"
    }, {
        "name": "TabletInputService",
        "status": "Running"
    }, {
        "name": "TapiSrv",
        "status": "Stopped"
    }, {
        "name": "TermService",
        "status": "Stopped"
    }, {
        "name": "Themes",
        "status": "Running"
    }, {
        "name": "TieringEngineService",
        "status": "Stopped"
    }, {
        "name": "TimeBrokerSvc",
        "status": "Running"
    }, {
        "name": "TokenBroker",
        "status": "Running"
    }, {
        "name": "TrkWks",
        "status": "Running"
    }, {
        "name": "TroubleshootingSvc",
        "status": "Stopped"
    }, {
        "name": "TrustedInstaller",
        "status": "Stopped"
    }, {
        "name": "tzautoupdate",
        "status": "Stopped"
    }, {
        "name": "UevAgentService",
        "status": "Stopped"
    }, {
        "name": "UmRdpService",
        "status": "Stopped"
    }, {
        "name": "upnphost",
        "status": "Stopped"
    }, {
        "name": "UserManager",
        "status": "Running"
    }, {
        "name": "UsoSvc",
        "status": "Running"
    }, {
        "name": "VacSvc",
        "status": "Stopped"
    }, {
        "name": "VaultSvc",
        "status": "Running"
    }, {
        "name": "vds",
        "status": "Stopped"
    }, {
        "name": "vmcompute",
        "status": "Running"
    }, {
        "name": "vmicguestinterface",
        "status": "Stopped"
    }, {
        "name": "vmicheartbeat",
        "status": "Stopped"
    }, {
        "name": "vmickvpexchange",
        "status": "Stopped"
    }, {
        "name": "vmicrdv",
        "status": "Stopped"
    }, {
        "name": "vmicshutdown",
        "status": "Stopped"
    }, {
        "name": "vmictimesync",
        "status": "Stopped"
    }, {
        "name": "vmicvmsession",
        "status": "Stopped"
    }, {
        "name": "vmicvss",
        "status": "Stopped"
    }, {
        "name": "VSS",
        "status": "Stopped"
    }, {
        "name": "VSStandardCollectorService150",
        "status": "Stopped"
    }, {
        "name": "W32Time",
        "status": "Stopped"
    }, {
        "name": "WaaSMedicSvc",
        "status": "Stopped"
    }, {
        "name": "WalletService",
        "status": "Stopped"
    }, {
        "name": "WarpJITSvc",
        "status": "Stopped"
    }, {
        "name": "wbengine",
        "status": "Stopped"
    }, {
        "name": "WbioSrvc",
        "status": "Stopped"
    }, {
        "name": "Wcmsvc",
        "status": "Running"
    }, {
        "name": "wcncsvc",
        "status": "Stopped"
    }, {
        "name": "WdiServiceHost",
        "status": "Running"
    }, {
        "name": "WdiSystemHost",
        "status": "Running"
    }, {
        "name": "WdNisSvc",
        "status": "Running"
    }, {
        "name": "WebClient",
        "status": "Stopped"
    }, {
        "name": "Wecsvc",
        "status": "Stopped"
    }, {
        "name": "WEPHOSTSVC",
        "status": "Stopped"
    }, {
        "name": "wercplsupport",
        "status": "Stopped"
    }, {
        "name": "WerSvc",
        "status": "Stopped"
    }, {
        "name": "WFDSConMgrSvc",
        "status": "Stopped"
    }, {
        "name": "WiaRpc",
        "status": "Stopped"
    }, {
        "name": "WinDefend",
        "status": "Running"
    }, {
        "name": "WinHttpAutoProxySvc",
        "status": "Running"
    }, {
        "name": "Winmgmt",
        "status": "Running"
    }, {
        "name": "WinRM",
        "status": "Stopped"
    }, {
        "name": "wisvc",
        "status": "Stopped"
    }, {
        "name": "WlanSvc",
        "status": "Stopped"
    }, {
        "name": "wlidsvc",
        "status": "Stopped"
    }, {
        "name": "wlpasvc",
        "status": "Stopped"
    }, {
        "name": "WManSvc",
        "status": "Stopped"
    }, {
        "name": "wmiApSrv",
        "status": "Stopped"
    }, {
        "name": "WMPNetworkSvc",
        "status": "Stopped"
    }, {
        "name": "workfolderssvc",
        "status": "Stopped"
    }, {
        "name": "WpcMonSvc",
        "status": "Stopped"
    }, {
        "name": "WPDBusEnum",
        "status": "Stopped"
    }, {
        "name": "WpnService",
        "status": "Running"
    }, {
        "name": "wscsvc",
        "status": "Running"
    }, {
        "name": "WSearch",
        "status": "Running"
    }, {
        "name": "wuauserv",
        "status": "Stopped"
    }, {
        "name": "WwanSvc",
        "status": "Stopped"
    }, {
        "name": "XblAuthManager",
        "status": "Running"
    }, {
        "name": "XblGameSave",
        "status": "Stopped"
    }, {
        "name": "XboxGipSvc",
        "status": "Stopped"
    }, {
        "name": "XboxNetApiSvc",
        "status": "Stopped"
    }, {
        "name": "AarSvc_7db15",
        "status": "Stopped"
    }, {
        "name": "BcastDVRUserService_7db15",
        "status": "Stopped"
    }, {
        "name": "BluetoothUserService_7db15",
        "status": "Stopped"
    }, {
        "name": "CaptureService_7db15",
        "status": "Running"
    }, {
        "name": "cbdhsvc_7db15",
        "status": "Running"
    }, {
        "name": "CDPUserSvc_7db15",
        "status": "Running"
    }, {
        "name": "ConsentUxUserSvc_7db15",
        "status": "Stopped"
    }, {
        "name": "CredentialEnrollmentManagerUserSvc_7db15",
        "status": "Stopped"
    }, {
        "name": "DeviceAssociationBrokerSvc_7db15",
        "status": "Stopped"
    }, {
        "name": "DevicePickerUserSvc_7db15",
        "status": "Stopped"
    }, {
        "name": "DevicesFlowUserSvc_7db15",
        "status": "Stopped"
    }, {
        "name": "LxssManagerUser_7db15",
        "status": "Stopped"
    }, {
        "name": "MessagingService_7db15",
        "status": "Stopped"
    }, {
        "name": "OneSyncSvc_7db15",
        "status": "Running"
    }, {
        "name": "PimIndexMaintenanceSvc_7db15",
        "status": "Running"
    }, {
        "name": "PrintWorkflowUserSvc_7db15",
        "status": "Running"
    }, {
        "name": "UdkUserSvc_7db15",
        "status": "Stopped"
    }, {
        "name": "UnistoreSvc_7db15",
        "status": "Running"
    }, {
        "name": "UserDataSvc_7db15",
        "status": "Running"
    }, {
        "name": "WpnUserService_7db15",
        "status": "Running"
    }
]